// app/api/admin/subcategories/route.ts

import { NextRequest, NextResponse } from "next/server";
import { connectDB } from "@/app/lib/mongodb";
import { Subcategory } from "@/app/models/brain/Subcategory";
import { Category }    from "@/app/models/brain/Category";
import { cookies }     from "next/headers";
import jwt             from "jsonwebtoken";

// ── Admin auth guard ──────────────────────────────────────────────────────────

async function requireAdmin(): Promise<{ userId: string } | null> {
  try {
    const cookieStore = await cookies();
    const token = cookieStore.get("token")?.value;
    if (!token) return null;
    const decoded = jwt.verify(token, process.env.JWT_SECRET!) as {
      userId: string;
      role:   string;
    };
    if (decoded.role !== "admin") return null;
    return { userId: decoded.userId };
  } catch {
    return null;
  }
}

// ── GET /api/admin/subcategories ──────────────────────────────────────────────
// Query params:
//   ?categoryId=xxx   (required — filter by parent category)
//   ?status=active|archived|deleted|all   (default: active+archived)
//   ?search=text
//   ?page=1
//   ?limit=50

export async function GET(req: NextRequest) {
  const admin = await requireAdmin();
  if (!admin) {
    return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });
  }

  await connectDB();

  const { searchParams } = new URL(req.url);
  const categoryId  = searchParams.get("categoryId") || "";
  const statusParam = searchParams.get("status")     || "all";
  const search      = searchParams.get("search")?.trim() || "";
  const page        = Math.max(1, parseInt(searchParams.get("page")  || "1"));
  const limit       = Math.min(100, Math.max(1, parseInt(searchParams.get("limit") || "50")));

  // categoryId is required
  if (!categoryId) {
    return NextResponse.json({ success: false, message: "categoryId is required" }, { status: 400 });
  }

  // Build filter
  const filter: Record<string, unknown> = { categoryId };

  if (statusParam === "all") {
    filter.status = { $in: ["active", "archived"] };
  } else {
    filter.status = statusParam;
  }

  if (search) {
    filter.name = { $regex: search, $options: "i" };
  }

  const total        = await Subcategory.countDocuments(filter);
  const subcategories = await Subcategory.find(filter)
    .sort({ displayOrder: 1, createdAt: -1 })
    .skip((page - 1) * limit)
    .limit(limit)
    .lean();

  return NextResponse.json({
    success: true,
    subcategories,
    pagination: {
      total,
      page,
      limit,
      pages: Math.ceil(total / limit),
    },
  });
}

// ── POST /api/admin/subcategories ─────────────────────────────────────────────
// Body: { categoryId, name, displayOrder, status }

export async function POST(req: NextRequest) {
  const admin = await requireAdmin();
  if (!admin) {
    return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });
  }

  await connectDB();

  try {
    const body = await req.json();
    const { categoryId, name, displayOrder = 0, status = "active" } = body;

    // Validate required fields
    if (!categoryId) {
      return NextResponse.json({ success: false, message: "categoryId is required" }, { status: 400 });
    }
    if (!name || typeof name !== "string" || name.trim().length === 0) {
      return NextResponse.json({ success: false, message: "Subcategory name is required" }, { status: 400 });
    }
    if (name.trim().length > 80) {
      return NextResponse.json({ success: false, message: "Name must be 80 characters or less" }, { status: 400 });
    }

    // Verify parent category exists
    const category = await Category.findById(categoryId);
    if (!category) {
      return NextResponse.json({ success: false, message: "Parent category not found" }, { status: 404 });
    }

    const subcategory = await Subcategory.create({
      categoryId,
      name:         name.trim(),
      displayOrder: Number(displayOrder) || 0,
      status,
      // slug auto-generated by pre-save hook
    });

    return NextResponse.json({ success: true, subcategory }, { status: 201 });

  } catch (error: any) {
    // Duplicate (categoryId + slug) compound index
    if (error.code === 11000) {
      return NextResponse.json(
        { success: false, message: "A subcategory with this name already exists in the selected category." },
        { status: 409 }
      );
    }
    console.error("CREATE SUBCATEGORY ERROR:", error);
    return NextResponse.json({ success: false, message: "Server error" }, { status: 500 });
  }
}

// ── PATCH /api/admin/subcategories — bulk reorder ─────────────────────────────
// Body: { updates: [{ id, displayOrder }, ...] }

export async function PATCH(req: NextRequest) {
  const admin = await requireAdmin();
  if (!admin) {
    return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });
  }

  await connectDB();

  try {
    const { updates } = await req.json();

    if (!Array.isArray(updates) || updates.length === 0) {
      return NextResponse.json({ success: false, message: "updates array required" }, { status: 400 });
    }

    const ops = updates.map(({ id, displayOrder }: { id: string; displayOrder: number }) => ({
      updateOne: {
        filter: { _id: id },
        update: { $set: { displayOrder: Number(displayOrder) } },
      },
    }));

    await Subcategory.bulkWrite(ops);
    return NextResponse.json({ success: true });

  } catch (error) {
    console.error("REORDER SUBCATEGORY ERROR:", error);
    return NextResponse.json({ success: false, message: "Server error" }, { status: 500 });
  }
}