// app/api/admin/categories/route.ts

import { NextRequest, NextResponse } from "next/server";
import { connectDB } from "@/app/lib/mongodb";
import { Category } from "@/app/models/brain/Category";
import { cookies } from "next/headers";
import jwt from "jsonwebtoken";

// ── Admin auth guard ──────────────────────────────────────────────────────────

async function requireAdmin(): Promise<{ userId: string } | null> {
  try {
    const cookieStore = await cookies();
    const token = cookieStore.get("token")?.value;
    if (!token) return null;
    const decoded = jwt.verify(token, process.env.JWT_SECRET!) as {
      userId: string;
      role: string;
    };
    if (decoded.role !== "admin") return null;
    return { userId: decoded.userId };
  } catch {
    return null;
  }
}

// ── GET /api/admin/categories ─────────────────────────────────────────────────
// Query params:
//   ?status=active|archived|deleted|all   (default: all except "deleted")
//   ?search=text
//   ?page=1
//   ?limit=50

export async function GET(req: NextRequest) {
  const admin = await requireAdmin();
  if (!admin) return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });

  await connectDB();

  const { searchParams } = new URL(req.url);
  const statusParam = searchParams.get("status") || "all";
  const search      = searchParams.get("search")?.trim() || "";
  const page        = Math.max(1, parseInt(searchParams.get("page") || "1"));
  const limit       = Math.min(100, Math.max(1, parseInt(searchParams.get("limit") || "50")));

  // Build filter
  const filter: Record<string, unknown> = {};

  if (statusParam === "all") {
    // Show active + archived but not deleted by default
    filter.status = { $in: ["active", "archived"] };
  } else {
    filter.status = statusParam;
  }

  if (search) {
    filter.name = { $regex: search, $options: "i" };
  }

  const total = await Category.countDocuments(filter);
  const categories = await Category.find(filter)
    .sort({ displayOrder: 1, createdAt: -1 })
    .skip((page - 1) * limit)
    .limit(limit)
    .lean();

  return NextResponse.json({
    success: true,
    categories,
    pagination: {
      total,
      page,
      limit,
      pages: Math.ceil(total / limit),
    },
  });
}

// ── POST /api/admin/categories ────────────────────────────────────────────────
// Body: { name, description, displayOrder, status }

export async function POST(req: NextRequest) {
  const admin = await requireAdmin();
  if (!admin) return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });

  await connectDB();

  try {
    const body = await req.json();
    const { name, description = "", displayOrder = 0, status = "active" } = body;

    if (!name || typeof name !== "string" || name.trim().length === 0) {
      return NextResponse.json({ success: false, message: "Category name is required" }, { status: 400 });
    }

    if (name.trim().length > 80) {
      return NextResponse.json({ success: false, message: "Name must be 80 characters or less" }, { status: 400 });
    }

    if (description && description.length > 500) {
      return NextResponse.json({ success: false, message: "Description must be 500 characters or less" }, { status: 400 });
    }

    const category = await Category.create({
      name:         name.trim(),
      description:  description.trim(),
      displayOrder: Number(displayOrder) || 0,
      status,
      // slug is auto-generated by pre-save hook in the schema
    });

    return NextResponse.json({ success: true, category }, { status: 201 });

  } catch (error: any) {
    // Duplicate slug error (code 11000)
    if (error.code === 11000) {
      return NextResponse.json(
        { success: false, message: "A category with this name already exists. Please use a different name." },
        { status: 409 }
      );
    }
    console.error("CREATE CATEGORY ERROR:", error);
    return NextResponse.json({ success: false, message: "Server error" }, { status: 500 });
  }
}

// ── PATCH /api/admin/categories — bulk reorder ────────────────────────────────
// Body: { updates: [{ id, displayOrder }, ...] }

export async function PATCH(req: NextRequest) {
  const admin = await requireAdmin();
  if (!admin) return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });

  await connectDB();

  try {
    const { updates } = await req.json();

    if (!Array.isArray(updates) || updates.length === 0) {
      return NextResponse.json({ success: false, message: "updates array required" }, { status: 400 });
    }

    const ops = updates.map(({ id, displayOrder }: { id: string; displayOrder: number }) => ({
      updateOne: {
        filter: { _id: id },
        update: { $set: { displayOrder: Number(displayOrder) } },
      },
    }));

    await Category.bulkWrite(ops);
    return NextResponse.json({ success: true });

  } catch (error) {
    console.error("REORDER CATEGORY ERROR:", error);
    return NextResponse.json({ success: false, message: "Server error" }, { status: 500 });
  }
}