// app/admin/users/[id]/page.tsx
// Dedicated full-page view for a single employee's complete activity.

"use client";

import { useEffect, useState, useCallback } from "react";
import { useParams, useRouter } from "next/navigation";
import {
  ArrowLeft, Calendar, Clock, Coffee, BookOpen, Keyboard,
  ChevronLeft, ChevronRight, Shield, Activity, TrendingUp,
  Zap, FileText, Target, AlertCircle, RefreshCw,
} from "lucide-react";

// ─── Types ────────────────────────────────────────────────────────────────────

type UserProfile = {
  _id:         string;
  fullName:    string;
  email:       string;
  status:      "active" | "suspended" | "banned";
  companyName: string;
  createdAt:   string;
  lastLogin:   string | null;
};

type Overview = {
  totalWorkLogs:            number;
  totalDiaryEntries:        number;
  totalTypingTests:         number;
  totalProductiveHours:     number;
  totalBreakHours:          number;
  avgProductiveHoursPerDay: number;
  typingHighestWpm:         number;
  typingAvgWpm:             number;
  typingTotalTests:         number;
};

type WorkLog = {
  _id:             string;
  date:            string;
  entryTime:       string | null;
  exitTime:        string | null;
  totalOfficeTime: number;
  totalBreakTime:  number;
  productiveTime:  number;
  breaks:          { type: string; duration: number; startTime: string }[];
  isHoliday:       boolean;
  notes:           string;
};

type DiaryEntry = {
  _id:       string;
  entryDate: string;
  heading:   string;
  content:   string;
  mood:      string | null;
  editCount: number;
  isLocked:  boolean;
};

type TypingResult = {
  _id:           string;
  timerDuration: number;
  typingMode:    string;
  wpm:           number;
  accuracy:      number;
  errors:        number;
  createdAt:     string;
};

type TimerStat = {
  timerDuration:   number;
  highestWpm:      number;
  highestAccuracy: number;
  totalTests:      number;
  totalWpmSum:     number;
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

// All system timestamps (createdAt, lastLogin, typing createdAt, etc.) are
// generated by the server with new Date() and stored correctly as UTC.
// These are displayed by converting to IST (UTC+5:30).

const IST = "Asia/Kolkata";

function secsToHHMM(secs: number): string {
  if (!secs) return "0h 0m";
  const h = Math.floor(secs / 3600);
  const m = Math.floor((secs % 3600) / 60);
  return `${h}h ${m}m`;
}

// For system-generated timestamps (createdAt, lastLogin) — stored correctly as UTC.
// Apply IST conversion: this is correct and intentional.
function fmtDate(iso: string | null | undefined): string {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleDateString("en-IN", {
      day: "2-digit", month: "short", year: "numeric",
      timeZone: IST,
    });
  } catch { return "—"; }
}

// For system-generated timestamps only (createdAt, lastLogin).
// NOT used for entryTime/exitTime — use fmtWorkTime for those.
function fmtTime(iso: string | null | undefined): string {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleTimeString("en-IN", {
      hour: "2-digit", minute: "2-digit", hour12: true,
      timeZone: IST,
    });
  } catch { return "—"; }
}

// ─── THE FIX ────────────────────────────────────────────────────────────────
//
// entryTime and exitTime are stored with IST hour values but no UTC offset
// subtraction was applied when saving. For example:
//   User clocks in at 10:30 AM IST
//   Stored as: 2026-04-02T10:30:00.000Z  ← IST time, wrongly tagged as UTC
//   Correct:   2026-04-02T05:00:00.000Z  ← what UTC should be
//
// If we use timeZone: "Asia/Kolkata", JS adds +5:30 on top of the already-IST
// stored value: 10:30 + 5:30 = 4:00 PM — 5.5 hours too late.
//
// Fix: read the raw UTC components (getUTCHours / getUTCMinutes) which contain
// the actual IST clock time as the developer stored it.
//
// This applies ONLY to entryTime and exitTime (and break startTime).
// Do NOT use this for system-generated fields — those are correct UTC.

function fmtWorkTime(iso: string | null | undefined): string {
  if (!iso) return "—";
  try {
    const d = new Date(iso);
    if (isNaN(d.getTime())) return "—";
    const h = d.getUTCHours();
    const m = d.getUTCMinutes();
    const ampm = h >= 12 ? "pm" : "am";
    const h12 = h === 0 ? 12 : h > 12 ? h - 12 : h;
    return `${String(h12).padStart(2, "0")}:${String(m).padStart(2, "0")} ${ampm}`;
  } catch { return "—"; }
}

// ─────────────────────────────────────────────────────────────────────────────

const STATUS_COLORS: Record<string, { text: string; bg: string; border: string }> = {
  active:    { text: "#22d3a0", bg: "rgba(34,211,160,0.12)",  border: "rgba(34,211,160,0.30)"  },
  suspended: { text: "#fbbf24", bg: "rgba(251,191,36,0.12)",  border: "rgba(251,191,36,0.30)"  },
  banned:    { text: "#f87171", bg: "rgba(248,113,113,0.12)", border: "rgba(248,113,113,0.30)" },
};

const MOOD_EMOJI: Record<string, string> = {
  happy: "😊", sad: "😢", angry: "😠", excited: "🤩", tired: "😴",
  stressed: "😰", calm: "😌", bored: "😑", motivated: "💪", anxious: "😬",
};

// ─── Spinner ──────────────────────────────────────────────────────────────────

function Spinner() {
  return (
    <div className="flex items-center justify-center h-40">
      <div
        className="w-7 h-7 rounded-full border-2 border-t-transparent animate-spin"
        style={{ borderColor: "var(--accent)", borderTopColor: "transparent" }}
      />
    </div>
  );
}

// ─── Pagination ───────────────────────────────────────────────────────────────

function Pagination({ page, totalPages, onPage }: {
  page: number; totalPages: number; onPage: (p: number) => void;
}) {
  if (totalPages <= 1) return null;
  return (
    <div className="flex items-center gap-2 justify-center mt-5">
      <button
        onClick={() => onPage(page - 1)} disabled={page <= 1}
        className="w-8 h-8 rounded-lg flex items-center justify-center border-none cursor-pointer disabled:opacity-30"
        style={{ background: "var(--surface2)", color: "var(--text3)" }}
      >
        <ChevronLeft size={14} />
      </button>
      {Array.from({ length: Math.min(totalPages, 7) }, (_, i) => i + 1).map(p => (
        <button key={p} onClick={() => onPage(p)}
          className="w-8 h-8 rounded-lg flex items-center justify-center border-none cursor-pointer text-[13px] font-mono"
          style={{
            background: p === page ? "var(--accent)" : "var(--surface2)",
            color:      p === page ? "#fff" : "var(--text3)",
            fontWeight: p === page ? 700 : 400,
          }}>
          {p}
        </button>
      ))}
      <button
        onClick={() => onPage(page + 1)} disabled={page >= totalPages}
        className="w-8 h-8 rounded-lg flex items-center justify-center border-none cursor-pointer disabled:opacity-30"
        style={{ background: "var(--surface2)", color: "var(--text3)" }}
      >
        <ChevronRight size={14} />
      </button>
    </div>
  );
}

// ─── Tab Button ───────────────────────────────────────────────────────────────

function TabBtn({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) {
  return (
    <button onClick={onClick}
      className="px-4 py-2 rounded-xl text-[13px] font-semibold border-none cursor-pointer transition-all"
      style={{
        background: active ? "rgba(232,67,147,0.15)" : "var(--surface2)",
        color:      active ? "var(--accent)" : "var(--text3)",
        border:     active ? "1px solid rgba(232,67,147,0.30)" : "1px solid transparent",
      }}>
      {label}
    </button>
  );
}

// ─── Work Logs Tab ────────────────────────────────────────────────────────────

function WorkLogsTab({ userId }: { userId: string }) {
  const [data,       setData]       = useState<WorkLog[]>([]);
  const [loading,    setLoading]    = useState(true);
  const [page,       setPage]       = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [from,       setFrom]       = useState("");
  const [to,         setTo]         = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const p = new URLSearchParams({ section: "work", page: String(page), limit: "15" });
      if (from) p.set("from", from);
      if (to)   p.set("to",   to);
      const res  = await fetch(`/api/admin/users/${userId}/fulldata?${p}`);
      const json = await res.json();
      if (json.success) {
        setData(json.workLogs);
        setTotalPages(json.pagination.pages || 1);
      }
    } finally { setLoading(false); }
  }, [userId, page, from, to]);

  useEffect(() => { load(); }, [load]);

  return (
    <div className="flex flex-col gap-4">
      {/* Date filters */}
      <div className="flex flex-wrap gap-3 items-center">
        {[
          { label: "From", val: from, set: (v: string) => { setFrom(v); setPage(1); } },
          { label: "To",   val: to,   set: (v: string) => { setTo(v);   setPage(1); } },
        ].map(({ label, val, set }) => (
          <div key={label} className="flex items-center gap-2">
            <span className="text-[12px]" style={{ color: "var(--text4)" }}>{label}</span>
            <input type="date" value={val} onChange={e => set(e.target.value)}
              className="border-none rounded-xl px-3 py-2 text-[13px] font-mono"
              style={{ background: "var(--surface2)", color: "var(--text2)" }} />
          </div>
        ))}
        {(from || to) && (
          <button onClick={() => { setFrom(""); setTo(""); setPage(1); }}
            className="px-3 py-1 rounded-lg text-[12px] border-none cursor-pointer"
            style={{ background: "rgba(248,113,113,0.12)", color: "var(--danger)" }}>
            Clear
          </button>
        )}
      </div>

      {loading ? <Spinner /> : data.length === 0 ? (
        <div className="text-center py-12" style={{ color: "var(--text4)" }}>No work logs found</div>
      ) : (
        <>
          <div className="flex flex-col gap-3">
            {data.map(log => (
              <div key={log._id} className="rounded-xl p-4"
                style={{ background: "var(--surface2)", border: "1px solid var(--border)" }}>

                {/* Row header */}
                <div className="flex flex-wrap items-center justify-between gap-2 mb-3">
                  <div className="flex items-center gap-2">
                    <Calendar size={13} style={{ color: "var(--accent)" }} />
                    <span className="font-mono font-bold text-[14px]" style={{ color: "var(--text)" }}>
                      {fmtDate(log.date)}
                    </span>
                    {log.isHoliday && (
                      <span className="px-2 py-0.5 rounded-full text-[10px] font-bold"
                        style={{ background: "rgba(96,165,250,0.15)", color: "#60a5fa", border: "1px solid rgba(96,165,250,0.25)" }}>
                        HOLIDAY
                      </span>
                    )}
                  </div>
                  <div className="flex items-center gap-3 text-[12px] font-mono">
                    <span style={{ color: "var(--green)" }}>⏱ {secsToHHMM(log.productiveTime)}</span>
                    <span style={{ color: "var(--amber)" }}>☕ {secsToHHMM(log.totalBreakTime)}</span>
                  </div>
                </div>

                {/* Times grid — only for non-holidays */}
                {!log.isHoliday && (
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mb-2">
                    {[
                      // ↓↓↓ THE KEY FIX: use fmtWorkTime (not fmtTime) for clock-in/out fields
                      { label: "Entry",       value: fmtWorkTime(log.entryTime),      color: "#60a5fa" },
                      { label: "Exit",        value: fmtWorkTime(log.exitTime),        color: "#f472b6" },
                      { label: "Office Time", value: secsToHHMM(log.totalOfficeTime), color: "var(--amber)" },
                      { label: "Breaks",      value: `${log.breaks?.length ?? 0} taken`, color: "var(--text3)" },
                    ].map(({ label, value, color }) => (
                      <div key={label} className="rounded-lg px-3 py-2"
                        style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
                        <div className="text-[10px] font-semibold uppercase tracking-wider mb-0.5"
                          style={{ color: "var(--text4)" }}>{label}</div>
                        <div className="font-mono text-[13px] font-semibold" style={{ color }}>{value}</div>
                      </div>
                    ))}
                  </div>
                )}

                {/* Break badges */}
                {log.breaks && log.breaks.length > 0 && (
                  <div className="flex flex-wrap gap-1.5 mt-1">
                    {log.breaks.map((b, i) => (
                      <span key={i} className="px-2 py-0.5 rounded-full text-[11px] font-mono"
                        style={{
                          background: b.type === "lunch" ? "rgba(245,158,11,0.12)"
                            : b.type === "tea" ? "rgba(34,211,160,0.10)" : "rgba(167,139,250,0.10)",
                          color: b.type === "lunch" ? "var(--amber)" : b.type === "tea" ? "var(--green)" : "#a78bfa",
                        }}>
                        {b.type === "lunch" ? "🥗" : b.type === "tea" ? "☕" : "⏸"}{" "}
                        {b.type} · {Math.round((b.duration ?? 0) / 60)}m
                        {/* ↓ Also fixed: show raw UTC hours for break start time */}
                        {b.startTime ? ` · ${fmtWorkTime(b.startTime)}` : ""}
                      </span>
                    ))}
                  </div>
                )}

                {log.notes && (
                  <div className="mt-2 text-[12px] px-3 py-2 rounded-lg"
                    style={{ background: "rgba(232,67,147,0.06)", color: "var(--text3)", border: "1px solid rgba(232,67,147,0.10)" }}>
                    📝 {log.notes}
                  </div>
                )}
              </div>
            ))}
          </div>
          <Pagination page={page} totalPages={totalPages} onPage={setPage} />
        </>
      )}
    </div>
  );
}

// ─── Diary Tab ────────────────────────────────────────────────────────────────

function DiaryTab({ userId }: { userId: string }) {
  const [data,       setData]       = useState<DiaryEntry[]>([]);
  const [loading,    setLoading]    = useState(true);
  const [page,       setPage]       = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [expanded,   setExpanded]   = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const p   = new URLSearchParams({ section: "diary", page: String(page), limit: "20" });
      const res  = await fetch(`/api/admin/users/${userId}/fulldata?${p}`);
      const json = await res.json();
      if (json.success) {
        setData(json.diaryEntries);
        setTotalPages(json.pagination.pages || 1);
      }
    } finally { setLoading(false); }
  }, [userId, page]);

  useEffect(() => { load(); }, [load]);

  return (
    <div className="flex flex-col gap-3">
      {loading ? <Spinner /> : data.length === 0 ? (
        <div className="text-center py-12" style={{ color: "var(--text4)" }}>No diary entries found</div>
      ) : (
        <>
          {data.map(entry => (
            <div key={entry._id} className="rounded-xl overflow-hidden"
              style={{ background: "var(--surface2)", border: "1px solid var(--border)" }}>
              <button
                onClick={() => setExpanded(expanded === entry._id ? null : entry._id)}
                className="w-full flex items-center justify-between p-4 border-none cursor-pointer text-left"
                style={{ background: "transparent" }}>
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0"
                    style={{ background: "rgba(232,67,147,0.12)" }}>
                    <BookOpen size={13} style={{ color: "var(--accent)" }} />
                  </div>
                  <div>
                    <div className="font-mono text-[13px] font-bold" style={{ color: "var(--text)" }}>
                      {fmtDate(entry.entryDate)}
                    </div>
                    <div className="text-[11px] mt-0.5 flex items-center gap-2" style={{ color: "var(--text4)" }}>
                      {entry.heading && <span>"{entry.heading}"</span>}
                      {entry.mood   && <span>{MOOD_EMOJI[entry.mood] || entry.mood}</span>}
                      <span>Edits: {entry.editCount}/5</span>
                      {entry.isLocked && <span style={{ color: "#f87171" }}>🔒 Locked</span>}
                    </div>
                  </div>
                </div>
                <ChevronRight size={14} style={{
                  color: "var(--text4)",
                  transform: expanded === entry._id ? "rotate(90deg)" : "none",
                  transition: "transform 0.2s",
                }} />
              </button>

              {expanded === entry._id && (
                <div className="px-4 pb-4">
                  <div className="rounded-xl p-4 text-[13px] leading-relaxed whitespace-pre-wrap"
                    style={{
                      background: "var(--surface)",
                      border: "1px solid var(--border2)",
                      color: "var(--text2)",
                      fontFamily: "monospace",
                      minHeight: "80px",
                    }}>
                    {entry.content || (
                      <span style={{ color: "var(--text4)", fontStyle: "italic" }}>Empty entry</span>
                    )}
                  </div>
                </div>
              )}
            </div>
          ))}
          <Pagination page={page} totalPages={totalPages} onPage={setPage} />
        </>
      )}
    </div>
  );
}

// ─── Typing Tab ───────────────────────────────────────────────────────────────

function TypingTab({ userId }: { userId: string }) {
  const [results,    setResults]    = useState<TypingResult[]>([]);
  const [timerStats, setTimerStats] = useState<TimerStat[]>([]);
  const [loading,    setLoading]    = useState(true);
  const [page,       setPage]       = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const p   = new URLSearchParams({ section: "typing", page: String(page), limit: "20" });
      const res  = await fetch(`/api/admin/users/${userId}/fulldata?${p}`);
      const json = await res.json();
      if (json.success) {
        setResults(json.typingResults);
        setTimerStats(json.timerStats || []);
        setTotalPages(json.pagination.pages || 1);
      }
    } finally { setLoading(false); }
  }, [userId, page]);

  useEffect(() => { load(); }, [load]);

  return (
    <div className="flex flex-col gap-5">
      {/* Per-timer bests */}
      {timerStats.filter(t => t.timerDuration !== 0).length > 0 && (
        <div>
          <div className="text-[11px] font-bold tracking-widest uppercase mb-3" style={{ color: "var(--text4)" }}>
            Per Timer Bests
          </div>
          <div className="flex flex-wrap gap-3">
            {timerStats.filter(t => t.timerDuration !== 0).map(ts => (
              <div key={ts.timerDuration} className="rounded-xl px-4 py-3 flex flex-col gap-1"
                style={{ background: "var(--surface2)", border: "1px solid var(--border)" }}>
                <div className="text-[11px] font-mono font-bold" style={{ color: "var(--accent)" }}>
                  {ts.timerDuration}s Timer
                </div>
                <div className="text-[13px] font-mono" style={{ color: "var(--text)" }}>
                  🏆 {ts.highestWpm} WPM · {ts.highestAccuracy}% acc
                </div>
                <div className="text-[11px]" style={{ color: "var(--text4)" }}>
                  {ts.totalTests} tests · avg {ts.totalTests > 0 ? Math.round(ts.totalWpmSum / ts.totalTests) : 0} WPM
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {loading ? <Spinner /> : results.length === 0 ? (
        <div className="text-center py-12" style={{ color: "var(--text4)" }}>No typing tests found</div>
      ) : (
        <>
          <div className="overflow-x-auto rounded-xl" style={{ border: "1px solid var(--border2)" }}>
            <table className="w-full border-collapse text-[13px]">
              <thead>
                <tr style={{ background: "var(--surface2)", borderBottom: "1px solid var(--border2)" }}>
                  {["Date & Time", "Timer", "Mode", "WPM", "Accuracy", "Errors"].map(h => (
                    <th key={h} className="text-left px-4 py-3 font-semibold tracking-wide"
                      style={{ color: "var(--text4)", fontSize: "11px", textTransform: "uppercase" }}>
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {results.map((r, i) => (
                  <tr key={r._id} style={{
                    background: i % 2 === 0 ? "var(--surface)" : "transparent",
                    borderBottom: "1px solid var(--border)",
                  }}>
                    <td className="px-4 py-2.5 font-mono text-[12px]" style={{ color: "var(--text3)" }}>
                      {/* typing createdAt is a system timestamp — correctly stored UTC, use IST display */}
                      {fmtDate(r.createdAt)}{" "}
                      <span style={{ color: "var(--text4)" }}>{fmtTime(r.createdAt)}</span>
                    </td>
                    <td className="px-4 py-2.5 font-mono font-bold" style={{ color: "var(--accent)" }}>
                      {r.timerDuration}s
                    </td>
                    <td className="px-4 py-2.5" style={{ color: "var(--text3)" }}>{r.typingMode}</td>
                    <td className="px-4 py-2.5 font-mono font-bold" style={{ color: "var(--green)" }}>{r.wpm}</td>
                    <td className="px-4 py-2.5 font-mono" style={{
                      color: r.accuracy >= 95 ? "var(--green)" : r.accuracy >= 80 ? "var(--amber)" : "var(--danger)" }}>
                      {r.accuracy}%
                    </td>
                    <td className="px-4 py-2.5 font-mono" style={{
                      color: r.errors === 0 ? "var(--green)" : r.errors <= 5 ? "var(--amber)" : "var(--danger)" }}>
                      {r.errors}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <Pagination page={page} totalPages={totalPages} onPage={setPage} />
        </>
      )}
    </div>
  );
}

// ─── Overview Tab ─────────────────────────────────────────────────────────────

function OverviewTab({ overview }: { overview: Overview }) {
  return (
    <div className="flex flex-col gap-5">
      {/* Work pattern */}
      <div>
        <div className="text-[11px] font-bold tracking-widest uppercase mb-3" style={{ color: "var(--text4)" }}>
          Work Pattern Summary
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          {[
            { icon: Activity, label: "Avg Productive / Day", value: `${overview.avgProductiveHoursPerDay}h`, color: "var(--green)", bg: "rgba(34,211,160,0.12)" },
            { icon: Zap,      label: "Typing Avg WPM",       value: overview.typingAvgWpm,                  color: "#a78bfa",       bg: "rgba(167,139,250,0.12)" },
            { icon: FileText, label: "Diary Written",         value: `${overview.totalDiaryEntries} pages`,  color: "#f472b6",       bg: "rgba(244,114,182,0.12)" },
          ].map(({ icon: Icon, label, value, color, bg }) => (
            <div key={label} className="rounded-xl p-4 flex flex-col gap-2"
              style={{ background: "var(--surface2)", border: "1px solid var(--border2)" }}>
              <div className="flex items-center gap-2">
                <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: bg }}>
                  <Icon size={13} style={{ color }} />
                </div>
                <span className="text-[11px] font-semibold tracking-widest uppercase" style={{ color: "var(--text4)" }}>{label}</span>
              </div>
              <div className="text-xl font-bold font-mono" style={{ color }}>{value}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Quick insights */}
      <div className="rounded-xl p-4 text-[13px] leading-relaxed"
        style={{ background: "rgba(245,158,11,0.07)", border: "1px solid rgba(245,158,11,0.18)" }}>
        <div className="font-semibold mb-2" style={{ color: "var(--amber)" }}>📊 Quick Insights</div>
        <ul className="flex flex-col gap-1.5 list-none p-0 m-0" style={{ color: "var(--text3)" }}>
          {[
            { emoji: "🗂", label: "Total work logs recorded",  value: `${overview.totalWorkLogs} days`,          color: "var(--text)"   },
            { emoji: "🕰", label: "Total productive time",     value: `${overview.totalProductiveHours}h`,        color: "var(--green)"  },
            { emoji: "☕", label: "Total break time taken",    value: `${overview.totalBreakHours}h`,             color: "var(--amber)"  },
            { emoji: "📔", label: "Diary entries written",     value: String(overview.totalDiaryEntries),         color: "#f472b6"       },
            { emoji: "⌨",  label: "Best typing speed",        value: `${overview.typingHighestWpm} WPM`,         color: "#a78bfa"       },
            { emoji: "🎯", label: "Total typing tests taken", value: String(overview.typingTotalTests),          color: "var(--text)"   },
          ].map(({ emoji, label, value, color }) => (
            <li key={label}>
              {emoji} {label}:{" "}
              <strong style={{ color }}>{value}</strong>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function UserDetailPage() {
  const params   = useParams<{ id: string }>();
  const router   = useRouter();
  const userId   = params.id;

  const [user,        setUser]       = useState<UserProfile | null>(null);
  const [overview,    setOverview]   = useState<Overview | null>(null);
  const [loading,     setLoading]    = useState(true);
  const [activeTab,   setActiveTab]  = useState<"overview" | "work" | "diary" | "typing">("overview");

  useEffect(() => {
    if (!userId) return;
    setLoading(true);
    fetch(`/api/admin/users/${userId}/fulldata?section=overview`)
      .then(r => r.json())
      .then(d => {
        if (d.success) {
          setUser(d.user as UserProfile);
          setOverview(d.overview);
        }
      })
      .finally(() => setLoading(false));
  }, [userId]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Spinner />
      </div>
    );
  }

  if (!user) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen gap-4">
        <AlertCircle size={40} style={{ color: "var(--danger)" }} />
        <div className="text-[16px] font-semibold" style={{ color: "var(--text3)" }}>Employee not found</div>
        <button onClick={() => router.push("/admin")}
          className="px-4 py-2 rounded-xl text-[13px] font-semibold border-none cursor-pointer"
          style={{ background: "var(--surface2)", color: "var(--text3)" }}>
          ← Back to Dashboard
        </button>
      </div>
    );
  }

  const sc = STATUS_COLORS[user.status] || STATUS_COLORS.active;

  return (
    <div className="flex flex-col gap-6 max-w-5xl mx-auto py-8 px-4">

      {/* ── Back button ── */}
      <button
        onClick={() => router.back()}
        className="flex items-center gap-2 self-start px-4 py-2 rounded-xl text-[13px] font-semibold border-none cursor-pointer transition-all"
        style={{ background: "var(--surface2)", color: "var(--text3)", border: "1px solid var(--border2)" }}
        onMouseEnter={e => (e.currentTarget as HTMLElement).style.color = "var(--accent)"}
        onMouseLeave={e => (e.currentTarget as HTMLElement).style.color = "var(--text3)"}
      >
        <ArrowLeft size={14} />
        Back to Dashboard
      </button>

      {/* ── User profile header ── */}
      <div
        className="rounded-2xl px-6 py-5 flex flex-col sm:flex-row items-start sm:items-center gap-5"
        style={{
          background:   "linear-gradient(135deg, rgba(232,67,147,0.10) 0%, rgba(96,165,250,0.07) 100%)",
          border:       "1px solid var(--border2)",
        }}
      >
        <div
          className="w-16 h-16 rounded-2xl flex items-center justify-center font-bold text-2xl shrink-0"
          style={{ background: "rgba(232,67,147,0.15)", color: "var(--accent)" }}
        >
          {user.fullName?.charAt(0)?.toUpperCase() || "?"}
        </div>

        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-3 flex-wrap mb-1">
            <h1 className="text-[22px] font-bold" style={{ color: "var(--text)" }}>{user.fullName}</h1>
            <span className="px-2 py-0.5 rounded-full text-[10px] font-bold"
              style={{ background: sc.bg, color: sc.text, border: `1px solid ${sc.border}` }}>
              {user.status?.toUpperCase()}
            </span>
          </div>
          <div className="text-[14px]" style={{ color: "var(--text3)" }}>
            {user.email}
            {user.companyName && (
              <span style={{ color: "var(--text4)" }}> · {user.companyName}</span>
            )}
          </div>
          <div className="flex gap-4 mt-1 text-[12px] font-mono flex-wrap" style={{ color: "var(--text4)" }}>
            {/* createdAt and lastLogin are system timestamps — IST display via fmtDate is correct */}
            <span className="flex items-center gap-1"><Calendar size={10} /> Joined {fmtDate(user.createdAt)}</span>
            <span className="flex items-center gap-1"><Activity size={10} /> Last login {fmtDate(user.lastLogin)}</span>
          </div>
        </div>
      </div>

      {/* ── Overview stat strip ── */}
      {overview && (
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
          {[
            { label: "Work Days",     value: overview.totalWorkLogs,              icon: Calendar,   color: "#60a5fa", bg: "rgba(96,165,250,0.12)"   },
            { label: "Prod. Hours",   value: `${overview.totalProductiveHours}h`, icon: TrendingUp, color: "var(--green)", bg: "rgba(34,211,160,0.12)" },
            { label: "Break Hours",   value: `${overview.totalBreakHours}h`,      icon: Coffee,     color: "var(--amber)", bg: "rgba(245,158,11,0.12)" },
            { label: "Diary Entries", value: overview.totalDiaryEntries,          icon: BookOpen,   color: "#f472b6", bg: "rgba(244,114,182,0.12)"   },
            { label: "Best WPM",      value: overview.typingHighestWpm,           icon: Keyboard,   color: "#a78bfa", bg: "rgba(167,139,250,0.12)"   },
            { label: "Typing Tests",  value: overview.typingTotalTests,           icon: Target,     color: "var(--accent)", bg: "rgba(232,67,147,0.12)" },
          ].map(({ label, value, icon: Icon, color, bg }) => (
            <div key={label} className="rounded-xl p-3 flex flex-col gap-1.5"
              style={{ background: "var(--surface)", border: "1px solid var(--border2)" }}>
              <div className="w-6 h-6 rounded-lg flex items-center justify-center" style={{ background: bg }}>
                <Icon size={11} style={{ color }} />
              </div>
              <div className="font-mono font-bold text-[18px]" style={{ color }}>{value}</div>
              <div className="text-[10px] font-semibold uppercase tracking-wider" style={{ color: "var(--text4)" }}>{label}</div>
            </div>
          ))}
        </div>
      )}

      {/* ── Section tabs ── */}
      <div className="flex gap-2 flex-wrap pb-1" style={{ borderBottom: "1px solid var(--border2)" }}>
        {(["overview", "work", "diary", "typing"] as const).map(tab => (
          <TabBtn key={tab} active={activeTab === tab} onClick={() => setActiveTab(tab)} label={
            tab === "overview" ? "🏠 Overview"
            : tab === "work"   ? "⏱ Work Logs"
            : tab === "diary"  ? "📔 Diary"
            : "⌨ Typing"
          } />
        ))}
      </div>

      {/* ── Tab content ── */}
      <div>
        {activeTab === "overview" && overview && <OverviewTab overview={overview} />}
        {activeTab === "work"                  && <WorkLogsTab userId={userId} />}
        {activeTab === "diary"                 && <DiaryTab    userId={userId} />}
        {activeTab === "typing"                && <TypingTab   userId={userId} />}
      </div>

    </div>
  );
}